### ISSUE TITLE
widget

### ISSUE THREAD

**Issue by guaka** [guaka/hitchticker#1]
/path/widget should be widget:
- for all messages
- also for messages per user?

**Comment by platschi** [comment]
yes, per user would be nice, so I can add e.g. a widget to my personal blog with "only" my own messages.

If that's what you meant :)

**Comment by guaka** [comment]
http://hitchticker.meteor.com/widget/uLHL6ik5AspPjPbSc is working now! I just hadn't deployed the above code yet!
