### ISSUE TITLE
Splitting tickers

### ISSUE THREAD

**Issue by UserStefan** [guaka/hitchticker#13]
I think we should take in concern from the beginning, that we need a function to split-up the tickers (to make it possible for everyone creating their personal ticker).

Means: Should be possible to have one ticker for the DTSG race. And another one for the abgefahren race. One for hitchgathering? And one for all?

Any ideas for a smart solution?

Only way in my head, to have a specific number/group/stream for each ticker.

**Comment by guaka** [comment]
I think it's best to stick to one ticker.
- It's easy to set up other tickers on another URL but this adds complexity and maintenance costs. And decreases overall visibility.
- Races are unlikely to be simultaneous.
- Each phone number costs 5 euro per month.

This could be a better way to do this:
- Define races
- Let users choose in which race they participate
- Add a stream per race, so you can e.g. get an URL like hitchticker.meteor.com/dtsg2015
  (but this should not be started before we have one successful race)

**Comment by UserStefan** [comment]
Okay, i think this is a good plan. I think the upcoming DTSG race and Abgefahren race can be seen as a beta test. 

I would also like to publish a personal stream on my website. In a couple of months.

**Comment by guaka** [comment]
ok so this is fine I guess

opened an issue for personal widget, #15
