### ISSUE TITLE
Cmon happy people

### ISSUE THREAD

**Issue by UserStefan** [guaka/hitchticker#14]
Deadline soon. We gonna get this till the DTSG race in 2 weeks?

**Comment by simison** [comment]
Seems like #9 is the only one to finish for this to really work already for a race.

**Comment by guaka** [comment]
here's the milestone for the race: https://github.com/guaka/hitchticker/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22DTSG+Competition+%22

if you have free text messages inside Germany it'd be great if you can test #9 and #11 - also works if you know someone with free SMS who's happy to try it of course :)
