### ISSUE TITLE
meteor.com deploy rights for others

### ISSUE THREAD

**Issue by guaka** [guaka/hitchticker#17]
- [x] for @simison (is that simison on meteor.com?)
- [x] meteor trustroots org (that I just created)

**Comment by simison** [comment]
@guaka ya, I'm simison also on meteor.com

**Comment by guaka** [comment]
not sure how to give other devs deploy rights, it is NOT at  https://www.meteor.com/account-settings/apps

**Comment by simison** [comment]
Type `meteor authorized help`

**Comment by guaka** [comment]
I ran `meteor authorized hitchticker.meteor.com --add trustroots`, can you
check if you have permission now? (through the org account)

**Comment by simison** [comment]
Yep! `meteor list-sites` shows hitchticker.

**Comment by guaka** [comment]
great!
