### ISSUE TITLE
SMS integration

### ISSUE THREAD

**Issue by guaka** [guaka/hitchticker#2]
let user enter phone number to link username with phone number?

**Comment by UserStefan** [comment]
philipp has something, that you culd send an sms with your username and your number was automatically registered. Afterwards it was possible to send messages.

**Comment by simison** [comment]
I've used Nexmo in the past and it works well:
https://www.nexmo.com/
https://www.twilio.com/

**Comment by guaka** [comment]
twilio didn't give me a DE number, trying nexmo now

**Comment by guaka** [comment]
stuck with http://stackoverflow.com/q/29447706/1245190 now

**Comment by guaka** [comment]
Yay! First test worked!

Our number is +491771789420

![screen shot 2015-04-04 at 18 24 41](https://cloud.githubusercontent.com/assets/54728/6993542/f4eda87a-daf7-11e4-8516-417094201afe.png)

**Comment by guaka** [comment]
works quite well now

todo: match phone number with user

**Comment by guaka** [comment]
continue with #9 and #11
