### ISSUE TITLE
Remove phoneconnector box temporarily - undo after 25th of May

### ISSUE THREAD

**Issue by badmadrabbit** [guaka/hitchticker#20]
Hey,
so we're gonna use the ticker for the race as it is - I removed the phone connector box from the main page so people who sign up don't sent loads of redundant text messages to verify their phone number. 

It worked for the stream page, but somehow in the profile it still shows up. Anyhow, if somebody can remove it from the profile page, would be nice
I will now stop to fuck up the code even more ;-)  

All my changes can be reverted after the race.

All the best

Jona

**Comment by simison** [comment]
Re-added this so that someone could easier implement that feature.
