### ISSUE TITLE
accounts / users?

### ISSUE THREAD

**Issue by guaka** [guaka/hitchticker#3]
now working: user/pass login

Facebook login? Twitter? these are relatively easy to add, but rather keep it as simple as possible (and no simpler)

should there be a "profile page" with the messages from the user?

**Comment by UserStefan** [comment]
FB and twitter i would add later.

Profile page with own messages seems good. Can we use this, to make a "personalization" (like only showing status updates of myself in the ticker on my blog, f.e.)?

**Comment by guaka** [comment]
so this is done, right?
